kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-argocd-cluster-argocd-application-controller-instana
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - update
      - create
      - list
      - delete
      - patch
  - apiGroups:
      - instana.io
    resources:
      - cores
      - units
    verbs:
      - update
      - create
      - list
      - delete
      - patch    
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-cntk-argocd-application-controller-instana
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-cntk-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-argocd-cluster-argocd-application-controller-instana