---
apiVersion: v1                      
kind: Namespace
metadata:
  name: multi-tenancy-gitops-channel-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: multi-tenancy-gitops-channel
  namespace: multi-tenancy-gitops-channel-ns
spec:
  type: Git
  pathname: 'https://github.com/rhacm-gitops/multi-tenancy-gitops.git'