apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-namespace-openshift-gitops
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures, PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration, PR.DS-2 Data-in-transit
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipPrune
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace-openshift-gitops-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: openshift-gitops
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: pipelines.openshift.io/v1alpha1
                kind: GitopsService
                metadata:
                  name: cluster
                  namespace: openshift-gitops
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-namespace-openshift-gitops
  namespace: rhacm-policies
placementRef:
  name: placement-policy-namespace-openshift-gitops
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-namespace-openshift-gitops
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-namespace-openshift-gitops
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
