apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: instana-agent-key
spec:
  data:
  - secretKey: instanaAgentKey
    remoteRef:
      key: 4d18cfd7-84ee-dbb5-7567-cfef62391453
  refreshInterval: 24h
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: instana-agent-key
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: instana
      type: Opaque
      data:
        key: "{{ .instanaAgentKey | toString }}"
